# Generated by Django 4.1 on 2022-08-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
