# Generated by Django 4.1 on 2022-08-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('date_and_hour', models.DateTimeField(verbose_name='Data e hora')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
