# Generated by Django 4.1 on 2022-08-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Dinheiro Extra')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Dinheiro extra',
                'verbose_name_plural': 'Dinheiros extras',
            },
        ),
    ]
