# Generated by Django 4.1 on 2022-09-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_category_name_alter_expense_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
