# Generated by Django 4.1 on 2022-09-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_wallet_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_and_hour',
            field=models.DateTimeField(help_text='use o seguinte formato: 15/06/2022 15:45', verbose_name='Data e hora'),
        ),
    ]
