# Generated by Django 4.1 on 2022-10-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_expense_date_and_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hour',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Data'),
        ),
    ]
