# Generated by Django 4.1 on 2022-10-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_wallet_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hour',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora'),
        ),
    ]
