# Generated by Django 4.1 on 2022-10-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_wallet_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='hour',
        ),
    ]
