# Generated by Django 4.1 on 2022-10-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_wallet_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='hour',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='date',
            field=models.DateField(null=True, verbose_name='Data'),
        ),
    ]
