# Generated by Django 4.1 on 2022-10-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_wallet_hour_alter_wallet_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('a pagar', 'A pagar'), ('pago', 'Pago')], max_length=7, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='hour',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora'),
        ),
    ]
