# Generated by Django 4.1 on 2022-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_expense_date_and_hour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraMoney',
        ),
    ]
