# Generated by Django 4.1 on 2022-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_delete_extramoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='proof',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Comprovante'),
        ),
    ]
