# Generated by Django 4.1 on 2022-10-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_expense_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='proof',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Comprovante'),
        ),
    ]
