# Generated by Django 4.1 on 2023-02-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_expense_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date_and_hour',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(help_text='Use o seguinte formato: 15/06/2022 15:45', null=True, verbose_name='Data'),
        ),
    ]
