# Generated by Django 4.1 on 2023-02-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_remove_expense_date_and_hour_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
